### ISSUE TITLE
I didn't get the point how to use your code.

### ISSUE THREAD

**Issue by rtransformation** [jchristopherson/nonlin#1]
Sorry to bother you:
   I'm a freshman of programming, I want use your codes to solve some nonlinear problem, but I didn't know how to use your code. Can you tell more specificly so that I can use your code...
                                                                                                                Thank you very much!

**Comment by jchristopherson** [comment]
What exactly don't you understand?  I'd be glad to help if you can provide some details about the issue you're having.

**Comment by rtransformation** [comment]
Please excuse me because I'm a new comer of programming, I don't know how to use your program,
for example, I have a set a nonlinear equation, what shoud I do next to use your subroutine to
calculate the roots of the equation set? I didn't really understand the content in the README.md

It would be so appreciated if you can give me a template.
                                                                                        Thank you very much.

**Comment by jchristopherson** [comment]
I've updated the README to include a complete program for both Fortran examples.  Hopefully this is sufficiently clear.  If not, please let me know.

**Comment by rtransformation** [comment]
Thank you very much, I've got the results, thank you again.
There still a lot to learn, thank you for your code~

**Comment by jchristopherson** [comment]
You're welcome.
